name: System-Info

on:
  push:

jobs:
  info-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display Current Date
        run: date

      - name: Display Hostname
        run: hostname

      - name: Display Operating System
        run: uname -a
